Make it possible to pass data to templates
vgno/roc pull request #163
Opened 2017-02-23 13:20 UTC by kjarmicki

This PR adds ability to pass additional data to templates that cannot or should not be obtained with questions.

My particular case is: I have a template inside of a module and I'd like to get that module's version from `package.json`.

2017-02-23 15:46 UTC, kjarmicki commented
Hm.. interesting, build failed on a file that I haven't touched. Not reproducable locally yet, but I'll keep trying :thinking:

2017-04-05 11:04 UTC, dlmr requested changes
Thanks for the PR and sorry for being slow on getting back to this.

I like the change, just some small comments on ways we can make it a little better.

2017-04-05 11:04 UTC, dlmr commented on docs/Templates.md
> +#### `data`
This section should be below `##### 'when'`.

2017-04-05 11:04 UTC, dlmr commented on docs/Templates.md
> +    "recentChanges": fetch("https://some-changelog.org/recent")
Given how the code is structured this example should be:
```js
"recentChanges":  () => fetch("https://some-changelog.org/recent")
```

2017-04-05 11:04 UTC, dlmr commented on src/commands/init/generateTemplate/collect.js
> +            metadata[key] = await dataProvider();
What do you think about passing in the `metadata` here, into `dataProvider()`?

Then we could get access to the answers that the user has answered.

```js
// Provide metadata
await dataProvider(metadata);

// Later we can use it
"recentChanges":  (answers) => fetch("https://some-changelog.org/recent")
```

If we do this change we should also add a comment about it in the documentation.

2017-04-05 11:59 UTC, kjarmicki commented on src/commands/init/generateTemplate/collect.js
> +            metadata[key] = await dataProvider();
Good point :)

2017-04-05 12:17 UTC, dlmr approved these changes

2017-04-05 12:19 UTC, merged